services:
  kowalski:
    build: .
    container_name: kowalski
    volumes:
      - ./telegram/props/lastfm.json:/usr/src/app/telegram/props/lastfm.json
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - kowalski
    depends_on:
      - postgres
      - ollama
    restart: always
  ollama:
    image: ollama/ollama
    container_name: kowalski-ollama
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - kowalski
    restart: always
  postgres:
    image: postgres:17
    container_name: kowalski-postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kowalski
      - POSTGRES_PASSWORD=kowalski
      - POSTGRES_DB=kowalski
    networks:
      - kowalski
    restart: always
  valkey:
    image: valkey/valkey
    container_name: kowalski-valkey
    networks:
      - kowalski
    restart: always
  # Most likely you won't need this
  #docs:
  #  build:
  #    context: ./docs
  #    dockerfile: Dockerfile
  #  container_name: kowalski-docs
  #  restart: always
  #  environment:
  #    - NODE_ENV=production
  #  networks:
  #    - kowalski

networks:
  kowalski: