# Do NOT use this Compose file in production. It exposes Kowalski's internal API
# and related services. In a server setup, it will expose everything to the
# public internet. Use only for development purposes.

services:
  kowalski:
    build: .
    container_name: kowalski
    ports:
      - "3000:3000"
    volumes:
      - ./telegram/props/lastfm.json:/usr/src/app/telegram/props/lastfm.json
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
  # Uncomment the following to test AI features
  #ollama:
  #  image: ollama/ollama
  #  container_name: kowalski-ollama
  #  volumes:
  #    - ./ollama:/root/.ollama
  #  ports:
  #    - "11434:11434"
  #  restart: always
  postgres:
    image: postgres:17
    container_name: kowalski-postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kowalski
      - POSTGRES_PASSWORD=kowalski
      - POSTGRES_DB=kowalski
    ports:
      - "5432:5432"
    restart: always
  valkey:
    image: valkey/valkey
    container_name: kowalski-valkey
    ports:
      - "6379:6379"
    restart: always
  # Most likely you won't need this
  #docs:
  #  build:
  #    context: ./docs
  #    dockerfile: Dockerfile
  #  container_name: kowalski-docs
  #  ports:
  #    - "3001:3000"
  #  restart: always
  #  environment:
  #    - NODE_ENV=development