services:
  kowalski:
    build: .
    container_name: kowalski
    volumes:
      - ./telegram/props/lastfm.json:/usr/src/app/telegram/props/lastfm.json
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - kowalski
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: kowalski-postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kowalski
      - POSTGRES_PASSWORD=kowalski
      - POSTGRES_DB=kowalski
    networks:
      - kowalski
  valkey:
    image: valkey/valkey
    container_name: kowalski-valkey
    networks:
      - kowalski

networks:
  kowalski: